global_defs {
  router_id call-cloud-sipproxy-1
  nftables keepalived-sipproxy
  script_user root
  enable_script_security
  max_auto_priority 0
}

vrrp_script chk_sip {
  script "/etc/keepalived/chk_sip.sh"
  interval 2
  weight -10
  timeout 3
  fall 2
  rise 2
}

vrrp_track_process chk_kamailio {
  process kamailio
  weight -10
}

vrrp_instance pbx_cloud {
  virtual_router_id 105
  advert_int 1
  priority 101
  state MASTER
  interface ens19
  use_vmac vip #00:00:5e:00:01:69 

  virtual_ipaddress { # VIPs
    192.168.10.10/25 dev ens19 
    172.16.30.15/24 dev eth0
  }

  authentication {
     auth_type PASS
     auth_pass Re@plica
     }
  track_script {
    chk_sip
  }
  
  track_process {
    chk_kamailio
  }

  vmac_xmit_base
  
  unicast_src_ip 172.16.30.13 # The IP address of this node
  unicast_peer { # list of IP addresses of other nodes
       172.16.30.14
    }

  notify_master "/etc/keepalived/notify.sh master"
  notify_backup "/etc/keepalived/notify.sh backup"
  notify_fault  "/etc/keepalived/notify.sh fault"
#   virtual_routes {
#     10.10.100.0/24 via 172.16.30.1 dev eth0

#   }
}

